[colors]
background = '#000000'
foreground = '#cccccc'
selection-background = '#282828'
selection-foreground = '#cccccc'
cursor = '#ffffff'
black = '#282828'
red = '#b76969'
green = '#719d72'
yellow = '#909858'
blue = '#68668f'
magenta = '#966894'
cyan = '#688891'
white = '#8e8e8e'
light-black = '#494949'
light-red = '#b87e7e'
light-green = '#839d84'
light-yellow = '#919864'
light-blue = '#73718f'
light-magenta = '#987397'
light-cyan = '#758c93'
light-white = '#aeaeae'
