[colors]
# Regular colors
background = '#101116'
foreground = '#e41951'
black = '#101116'
red = '#ff0051'
green = '#01dc84'
yellow = '#faf945'
blue = '#0271b6'
magenta = '#c930c7'
cyan = '#00c5c7'
white = '#c7c7c7'

# Bright / light colors
light-black = '#686868'
light-red = '#ff6e67'
light-green = '#60fa68'
light-yellow = '#fffc67'
light-blue = '#6871ff'
light-magenta = '#bd35ec'
light-cyan = '#60fdff'
light-white = '#ffffff'

# Cursor
cursor = '#76ff9f'
vi-cursor = '#76ff9f'

# Selection
selection-background = '#c1deff'
selection-foreground = '#000000'
