[colors]
background = '#000000'
foreground = '#ffffff'
cursor = '#435d75'
black = '#393939'
red = '#da4939'
green = '#9acc79'
yellow = '#d0d26b'
blue = '#6d9cbe'
magenta = '#9f5079'
cyan = '#435d75'
white = '#c2c2c2'
light-black = '#474747'
light-red = '#ff6c5c'
light-green = '#8fb676'
light-yellow = '#c8bc45'
light-blue = '#d0d0ff'
light-magenta = '#a761c2'
light-cyan = '#6e98a4'
light-white = '#c2c2c2'
