#!/usr/bin/env bash

due_now=$(task due.after:now-10min due.by:now status:pending count)
if [ "$due_now" -gt 0 ]; then
  notify-send -u normal -i capacities "Taskwarrior" "!!!TASK!!! - $(task due.after:now-10min due.by:now status:pending export | jq -r '.[].description')"
fi
