#!/usr/bin/env bash

due_now=$(task due.before:now+12h status:pending count)
if [ "$due_now" -gt 0 ]; then
  notify-send -u normal -i capacities "Taskwarrior" "!!!TASK!!! - $(task due.before:now+12h status:pending export | jq -r '.[].description')"
fi
