#!/usr/bin/env bash

due_now=$(task due.after:now-10min due.by:now count)
if [ "$due_now" -gt 0 ]; then
  notify-send -u normal -i capacities "Taskwarrior" "TASK!!! - $(task due.after:now-10min due.by:now export | jq -r '.[].description')"
fi
